# Generated by Django 4.1.5 on 2023-01-31 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Downloder_app', '0002_task_progress_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(default='Pending', max_length=10),
        ),
    ]
